### ISSUE TITLE
Fix build problems caused by DifferentialEquations

### ISSUE THREAD

**Issue by davidanthoff** [davidanthoff/IterableTables.jl#31]
There is some problem related to PyDSTool, see the build log [here](https://travis-ci.org/davidanthoff/IterableTables.jl/jobs/228997663).

@ChrisRackauckas, any idea what I should do here? Ideally I would like to pull less of the whole differential equation ecosystem in as a [testing dependency](https://github.com/davidanthoff/IterableTables.jl/blob/master/test/REQUIRE), but I'm don't understand the whole package split and what I minimally need so that [this](https://github.com/davidanthoff/IterableTables.jl/blob/master/test/test_integration_differentialequations.jl) runs.

**Comment by ChrisRackauckas** [comment]
Change

```julia
using DifferentialEquations
using ParameterizedFunctions
```

to

```julia
using DiffEqBase, OrdinaryDiffEq
```

You should only need to depend on `DiffEqBase`, with `OrdinaryDiffEq` as a test dependency. Then you should be good.

**Comment by davidanthoff** [comment]
Cool, that fixed it, thanks!
