### ISSUE TITLE
Integrate with Parquet.jl

### ISSUE THREAD

**Issue by davidanthoff** [davidanthoff/IterableTables.jl#49]
https://github.com/JuliaComputing/Parquet.jl first needs to be update to work on julia 0.6 and Windows.

**Comment by s-celles** [comment]
Parquet.jl is now available under julia 0.6 not sure although it's working with Windows 

https://github.com/JuliaComputing/Parquet.jl/issues/17

**Comment by davidanthoff** [comment]
Already done: https://github.com/davidanthoff/ParquetFiles.jl.
