### ISSUE TITLE
Avoid type piracy

### ISSUE THREAD

**Issue by quinnj** [davidanthoff/IterableTables.jl#75]
I think it would be a little more kosher for types like DataFrame to implement `collect(e::Enumerable, ::Type{DataFrame})` (which would be a more specific method than the [default fallback](https://github.com/davidanthoff/Query.jl/blob/63bb596765516947c43257221f2dc57e68e61320/src/sinks/sink_type.jl#L1)) instead of stealing the `DataFrame(x::Any)` [definition](https://github.com/davidanthoff/IterableTables.jl/blob/646977c047bf9d0d3898187fd61663dcab2bfcf2/src/integrations/dataframes-missing.jl#L127).

**Comment by davidanthoff** [comment]
Closing as the constructor approach now seems widely accepted, plus the code for DataFrames.jl now lives in DataFrames.jl itself, so no more type piracy there.
