### ISSUE TITLE
DataTable is deprecated

### ISSUE THREAD

**Issue by femtotrader** [davidanthoff/IterableTables.jl#82]
Hello,

Doc of IterableTables is mentioning https://github.com/JuliaData/DataTables.jl but it's deprecated.
Maybe doc should be updated accordingly

Kind regards

**Comment by davidanthoff** [comment]
I'm dropping support on julia 0.7 (because DataTables.jl doesn't work on 0.7), but things should still work on julia 0.6, so I don't think we need to adjust anything here?
