### ISSUE TITLE
Ambiguity with `TimeSeries`

### ISSUE THREAD

**Issue by ValentinKaisermayer** [davidanthoff/IterableTables.jl#95]
See: https://github.com/JuliaStats/TimeSeries.jl/issues/438

The `TimeArray` constructor
https://github.com/queryverse/IterableTables.jl/blob/2683c006134613131c1f747c0f0fa40ec6e49bf0/src/integrations/timeseries.jl#L51
has some ambiguity with the constructor in `TimeSeries`.

Thanks!

**Comment by davidanthoff** [comment]
Thanks for reporting! I just tagged a new release that should fix this.
